### ISSUE TITLE
Creating File/Directory Background is above

### ISSUE THREAD

**Issue by NullGang** [Night-Star04/vscode-fluent-ui#10]
![{8487ADD9-24EE-49CD-A1B3-EFD6356FB1A2}](https://github.com/user-attachments/assets/95325c98-41d8-4072-9bbd-a5da66194e84)
This happens.

**Comment by Night-Star04** [comment]
Hello @NullGang,

Apologies for the delayed response. Regarding the Creating File/Directory Background is above issue, I will be working on a fix shortly. Please stay tuned!

**Comment by Night-Star04** [comment]
I have studied the input div for Creating File/Directory. Would the CSS below achieve the desired effect?

```css
.explorer-folders-view .explorer-item .monaco-inputbox {
    padding: 0 !important;
}
```
