### ISSUE TITLE
Editor container hover content widget isn't displayed correctly

### ISSUE THREAD

**Issue by Night-Star04** [Night-Star04/vscode-fluent-ui#36]
The content of the hover content widget is not displayed correctly at the bottom, causing the content to overflow and become invisible.
Additionally, the padding on all four sides appears inconsistent and unusual.

### Screenshot:
![Image](https://github.com/user-attachments/assets/a0f3ba91-e7b4-410d-b9e6-8aecc169c1cb)
![Image](https://github.com/user-attachments/assets/c75bfb9c-c814-4478-8efd-d3a254dd2624)

### System Information:
OS: Windows 11 23H2
Vs Code: 1.97.2 (user setup)
Extension Version: 4.5.0 (latest)

**Comment by Mukul1127** [comment]
I'm pretty sure this is because the padding is being applied equally to all 4 sides but the width and height is set on the element as if there is no padding so the bottom and right are clipped off.

**Comment by Night-Star04** [comment]
> I'm pretty sure this is because the padding is being applied equally to all 4 sides but the width and height is set on the element as if there is no padding so the bottom and right are clipped off.

Yes, the issue is indeed caused by the padding. The width and height are not set separately. Maybe removing the related padding settings could be a possible solution?

**Comment by Night-Star04** [comment]
Relevant CSS selectors:  
```css
/* Original, with some plain div elements removed */
#workbench\.parts\.editor > div.content div.monaco-scrollable-element > div.split-view-container div.monaco-scrollable-element > div.split-view-container div.editor-container div.overflowingContentWidgets > div.monaco-resizable-hover > div.monaco-hover.fade-in.hidden

/* From workbench.desktop.main.css */
.monaco-editor .monaco-resizable-hover > .monaco-hover
```

Affected CSS style source:
https://github.com/Night-Star04/vscode-fluent-ui/blob/850eecdcda6e62b80a27b498344461545c7a6f31/src/css/editor_chrome.css#L999-L1001

**Comment by Mukul1127** [comment]
> > I'm pretty sure this is because the padding is being applied equally to all 4 sides but the width and height is set on the element as if there is no padding so the bottom and right are clipped off.
> 
> Yes, the issue is indeed caused by the padding. The width and height are not set separately. Maybe removing the related padding settings could be a possible solution?

At least for me, the width and height were inlined. Removing the padding fixes it but it's not exactly the best solution. I'm trying to find a solution because it's annoying to see everytime.

**Comment by Mukul1127** [comment]
Also for me, removing inline width and height partially fixes it. It's the correct size, but the border doesn't show up on the right and bottom. Here's a video: https://imgur.com/a/F8ryv6y

**Comment by Mukul1127** [comment]
Could you try this fix, ideally we should fix the `.monaco-sash` in `.monaco-resizable-hover` but I think we would need javascript for that. Instead this just hides the border created by `.monaco-sash` and uses it's own. I think it's identical.
```
/* Fix Tooltips */
.monaco-editor .monaco-resizable-hover > .monaco-hover {
    height: auto !important;
    width: auto !important;
    border: 1px solid var(--vscode-editorHoverWidget-border) !important;
}
.monaco-editor .monaco-resizable-hover {
    border: none !important;
}
```

**Comment by Night-Star04** [comment]
Thanks for the video and the CSS fix! The workaround works well, and the content is now displaying correctly on my end too.  

Regarding the JavaScript part, I just checked the elements, and perhaps we could dynamically get the size of `.monaco-hover` and then set the size of `.monaco-resizable-hover` accordingly? Since `.monaco-sash` takes the dimensions from `.monaco-resizable-hover`, this might solve the issue more elegantly.

**Comment by Mukul1127** [comment]
> Thanks for the video and the CSS fix! The workaround works well, and the content is now displaying correctly on my end too.
> 
> Regarding the JavaScript part, I just checked the elements, and perhaps we could dynamically get the size of `.monaco-hover` and then set the size of `.monaco-resizable-hover` accordingly? Since `.monaco-sash` takes the dimensions from `.monaco-resizable-hover`, this might solve the issue more elegantly.

That's exactly what I was thinking, though either solution is fine I think, they look virtually the same.

**Comment by Night-Star04** [comment]
The difference between the two border settings:  

- Using `.monaco-hover`:  
  ![Image](https://github.com/user-attachments/assets/cd17b9c4-efae-446b-b2f0-cb916973db8d)

- Using `.monaco-resizable-hover` (with manually set values, so there might be some variations):  
  ![Image](https://github.com/user-attachments/assets/642c79e6-d574-4829-b0be-c56efb21f17d)

From what I can see, the only noticeable difference is in the way the right and bottom borders are displayed. However, this difference is minimal and shouldn't significantly impact the overall visual appearance.  

Additionally, if we go with the `.monaco-resizable-hover` approach, we would also need to **reposition the right and bottom `.monaco-sash`**. Combined with the necessary calculations in JavaScript, it seems like this solution might be a bit overcomplicated and not very efficient.

**Comment by Night-Star04** [comment]
Recently, I've noticed that some text gets covered by the **VSCode hover widget** while using it.  
![Image](https://github.com/user-attachments/assets/020c416a-4285-45df-8974-7970235de4c0)

If I remove `height: auto !important;`, the text appears correctly.  
![Image](https://github.com/user-attachments/assets/449491d4-ae4e-41d0-a109-6647fda60edd)

This might slightly affect readability, but it doesn't seem too problematic. Perhaps we could also consider ways to improve this?

**Comment by Night-Star04** [comment]
Additionally, regarding the **action section** inside the VSCode hover widget, it currently has a dark gray background. Perhaps we could remove it to make the appearance more consistent?  

![Image](https://github.com/user-attachments/assets/1bc3be38-2348-46f9-b7bf-4400a896857b)

### **Affected CSS Style:**  
```css
.monaco-editor .monaco-hover .hover-row .actions {
    background-color: var(--vscode-editorHoverWidget-statusBarBackground);
}
```

**Comment by Mukul1127** [comment]
> Recently, I've noticed that some text gets covered by the **VSCode hover widget** while using it. ![Image](https://github.com/user-attachments/assets/020c416a-4285-45df-8974-7970235de4c0)
> 
> If I remove `height: auto !important;`, the text appears correctly. ![Image](https://github.com/user-attachments/assets/449491d4-ae4e-41d0-a109-6647fda60edd)
> 
> This might slightly affect readability, but it doesn't seem too problematic. Perhaps we could also consider ways to improve this?

I think no matter what we might have to use JavaScript to fix this. Translate-y doesn't work since it's irrelevant of the line height. I can start working on a script.

**Comment by Mukul1127** [comment]
Here's the final CSS I arrived on, all `!important`s are required, everything done as elegantly as I could figure out:
```css
/* Fix Tooltips */
/* Remove width and height cap and make custom border */
.monaco-editor .monaco-resizable-hover > .monaco-hover {
    height: auto !important;
    width: auto !important;
    border: 1px solid var(--vscode-editorHoverWidget-border) !important;
}
/* Remove original border and move upwards to account for padding */
.monaco-editor .monaco-resizable-hover {
    border: none;
    transform: translateY(-1.5rem);
}
/* Remove random buttons at the edges that don't seem to do anything */
.monaco-editor .monaco-sash {
    display: none;
}
/* Make background of action buttons transparent */
.monaco-editor .monaco-resizable-hover > .monaco-hover .hover-row .actions {
    background-color: transparent;
}
/* Make hr-like lines vertically centered */
.monaco-editor .monaco-resizable-hover > .monaco-hover .monaco-hover-content > * + * {
    padding-top: 0.25rem;
    margin-top: 0.25rem !important;
}
```
![Image](https://github.com/user-attachments/assets/9b362453-0779-4393-a03b-5d640e20d198)
