### ISSUE TITLE
Bottom panel input box text not centered

### ISSUE THREAD

**Issue by Night-Star04** [Night-Star04/vscode-fluent-ui#38]
The text in the input box at the bottom panel should be horizontal centered, but it is shifted downward, making it look a bit off.

![Image](https://github.com/user-attachments/assets/27634ebb-5c51-4609-a2f9-e20f942a99a0)

**Comment by Night-Star04** [comment]
Relevant CSS selectors:
```css
/* Original, with some plain div elements removed */
#workbench\.parts\.panel > div.composite.title.has-composite-bar > div.title-actions li.action-item.viewpane-filter-container.grow div.monaco-inputbox.idle > div > input

/* From workbench.desktop.main.css */
.monaco-inputbox > .ibwrapper > .input
```

Affected CSS style source:
1. From workbench.desktop.main.css 
```css
.monaco-inputbox>.ibwrapper>.input, .monaco-inputbox>.ibwrapper>.mirror {
    padding: 4px 6px;
}
```
2. Form editor_chrome.css
https://github.com/Night-Star04/vscode-fluent-ui/blob/baec3a5b1b728546c48bfe8037f6fe2a19104fcb/src/css/editor_chrome.css#L1054-L1072
