### ISSUE TITLE
Github Copilot Compatibility

### ISSUE THREAD

**Issue by Cleboost** [Night-Star04/vscode-fluent-ui#56]
Hello, do you think it's possible to make the github copilot extension compatible so that the background is also translucent?
![Image](https://github.com/user-attachments/assets/9f202599-7294-4f2a-a2a6-c6bf23407276)

**Comment by Night-Star04** [comment]
Thanks for the suggestion!
Things have been a bit hectic on my end lately, but I’ll get to this as soon as I can. Thanks for your patience!🙏

**Comment by Cleboost** [comment]
Thx for your reply ! No problem, take your time. your extensions are really beautiful

**Comment by Night-Star04** [comment]
Sorry to keep you waiting. I looked into part of it. Will the CSS below achieve the effect you want?

```css
.monaco-workbench .part.auxiliarybar {
    background: transparent !important;
    background-blend-mode: exclusion;
    overflow-y: auto;
    height: var(--content-height);

    > .composite.title {
        background-color: transparent;
        padding-left: var(--s4) !important;
        padding-right: 0 !important;

        > .composite-bar-container .action-item {
            border-radius: var(--border-radius) var(--border-radius) 0 0 !important;
            border-top: transparent !important;
            border: 1px solid transparent !important;
            transition: borderRadius var(--easing-timing-fast) var(--easing-curve-in),
                transform var(--easing-timing-fast) var(--easing-curve-in);
            will-change: borderRadius;
        }
        .action-item {
            overflow: hidden;
            position: relative;
            z-index: 1;
        }
    }

    > .content {
        background: var(--noise-bg) repeat var(--card-bg) !important;
        border-radius: var(--border-radius);
        padding: var(--s2) var(--s3) 0;
        width: calc(100% - var(--s4)) !important;
    }
}

.part.right {
    margin-right: var(--s3) !important;
}
```
